name: controle_gastos_app
description: "App de controle de gastos com automação via notificações."
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  provider: ^6.0.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
