name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
    
    - name: Instalar dependências
      run: flutter pub get
    
    - name: Limpar projeto
      run: flutter clean
    
    - name: Build APK
      run: flutter build apk --release
