name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
    
    - name: Clean project
      run: |
        flutter clean
        rm -rf .dart_tool/
        cd android
        if [ -f "gradlew" ]; then
          chmod +x gradlew
          ./gradlew clean
        fi
        cd ..
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build APK
      run: flutter build apk --release
